version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
      - "5001:5001"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
      - "5001:5001"
    depends_on:
      - database
    env_file:
      - ./backend/.env

  database:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
